[package]
name = "curvessurfaces"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.24"
log = "0.4.17"
nalgebra = "0.31.1"
simple_logger = "2.3.0"
wgpu = { version = "0.13.0" }
winit = { version = "0.27.2" }
